### PR TITLE
Add support to rotate vertices.

### PR DESCRIPTION
**Pull request by leorosa**
This code allows the rotation of points around a custom axis, using as center of rotation a given position. The reference used to implement points transformation was found here:

    http://www.vtk.org/doc/nightly/html/classvtkTransform.html

I've mostly read how you have implemented points move (which was what I have intended as "translation", written in the other message), and adjusted it accordingly to rotate them. This feature is mostly meaningful if the geometry (or parts of it) isn't aligned to the cartesian directions.

If you find it useful, please consider to pull it in your repository. (Sorry about the icon).

Thanks,
Leonardo

### CODE REVIEW

**Comment by nicolasedh** [comment]
Hi!

It looks really nice! But I can't compile. I've just had a quick look but it looks like you've made changes to MainWindow.ui which hasn't been included in the pull request. Or maybe I messed up some how. Could you please check?

Best Regards
Nicolas

**Comment by leorosa** [comment]
Sorry, I forgot to include this file. Now it is updated, as in commit

https://github.com/leorosa/hexBlocker/commit/cb33482f6d5644c30b8f5540ce90d983790af0aa

Do I need to do a 'pull request' again?

**Comment by nicolasedh** [comment]
Hi, very nice change! 

So nice I just had to create another of my icons. Yes they still look like a child made them but I kind of like them =)

I also liked the change of increasing the number of decimal places in extrude.
Nicolas

**Comment by leorosa** [comment]
Thanks!

The icons are nice -- far better than a 'R'.

Regarding the decimal places: a fellow here complained about this limitation, when doing a small mesh. Not everybody likes to use millimeters.

I was thinking in 'divulge' your program among researchers that I know (I find hexBlocker really useful). Would you mind to make a description of it, perhaps with a screenshot, in your repository?

Best regards,
Leonardo

**Comment by nicolasedh** [comment]
Hi,

Sorry in being late in replying! I'll see what I can do. I remember writing something on cfd-online.
And I started the thread with a couple of screen shots. I even wrote a short tutorial here:

http://www.cfd-online.com/Forums/openfoam-meshing/114773-hexblocker-gui-blockmeshdict-alpha-release-2.html#post452986 

Although my filosofi is that no tutorial should be needed. A program should be so intuitive that users don't ask for a tutorial or manual. The only requirement I want is that users know something of OpenFOAM and blockMesh before starting with hexblocker.

It really makes me glad to hear that your collegues might be interested. But instead of some screen shots why not just show them how it works?

Best Regards
Nicolas

**Comment by leorosa** [comment]
No problem, there is no rush.

I came with the suggestion for a description, because at a first sight someone may have the wrong impression of the program. Just a list of the features, and maybe a screenshot, can make a huge difference for someone that reaches your page, and attract more attention, I think. Here, I can show hexBlocker in action -- it is intuitive.

Best regards,
Leonardo Rosa

**Pull request merged**
