### PR TITLE
Scale geometry

### PR DESCRIPTION
**Pull request by leorosa**
Hi Nicolas,

I have just finished more changes. With them, now the value of convertToMeters is stored in HexBlocker class. It can be set both in "View/Set Scale" menu, or entering a value at the top of vertices list.

There is also a checkbox above the vertices list, which allows to scale the geometry. The applied scale is also stored, and it is recovered (set to 1) when the checkbox is un-checked. The logic behind it may be tricky, and surely it need more tests...

Thanks for your guidance with the code!
Leonardo Rosa

### CODE REVIEW

**Comment by nicolasedh** [comment]
Nice!

I'm happy to guide. Although you seem to manage rather well with a minumum of guidence. I'm just happy  that you are improving the code!

However I get a compilation error: 
` error: ‘class Ui::VerticeEditorWidget’ has no member named ‘scaleGeometry’
`
Did you include the latest version VerticeEditorWidget.ui? Or have I missed something?

/N

**Comment by leorosa** [comment]
Sorry, I forgot to upload VerticeEditorWidget.ui. It is updated now.

**Comment by nicolasedh** [comment]
Hi,

Looks like I'm missing the new VerticeEditorWidget.h . 

I usually keep a terminal open in the source dir then do a 
`git status`

before comiting. Any thing in read is usually something I missed ;-)

But then again, I don't know where you are but here it's kind of late so I do understand if we missed something. And on that note I'll hit the bed! Let's continue this tomorrow. At least I will =).

I'll be online tomorrow evening at the earliest, long work day tomorrow, with meetings. 

/N

**Comment by leorosa** [comment]
Heh, the problem is, I'm new to using git. I believe I need a better way to remember which files had been changed, to include all of them in

`git add`

Again, sorry for the inconvenience. Luckily there is some more time to spend here in Brazil.

**Comment by nicolasedh** [comment]
Hi,

I think having the convertToMeters dialog above vertices is really good. 

However I believe I was wrong when saying we needed another member variabel. 
`GeoActor->SetUserTransform(sf,sf,sf)`
Will fix all those issues for us. So we don't really need to keep track of all previous scales.

I'll push a change soon.

/N

**Comment by nicolasedh** [comment]
Ah your're in brazil that explains the late hours (in my time frame). Myself live in Sweden so I guess we have a some ahours between us =). Git has a bit of a learning curve but I've come to like even the most basic operations alot. If you have 15 minutes to spare try.github.io/ is quie fun.

Actually, once I've changed the code a bit I started thinking. 
Do we ever want to use the same scalefactor for the geometry as convertToMeters?

Let say a have a geometry in mm. Then it would make sens to keep writing the coordinates in mm but set the convertToMeters to 1e-3. So I would not wan't to scale the geometry at all. Or use a factor of 1.

Let's say the STL is in meters but I don't like to use the comma sign so I prefer to work in mm and write vertice coordinates as mm. And I want to use convertToMeters so blockMesh scales the mesh back to m. Then convertToMeters would be 1e-3 and I would probably like to scale the STL but with 1/convertToMeters. 

I guess the sensible thing would be ta have one textbox for convertToMeters and one for scale factor for the geometry.

Have I missed something? What do you think?

I've changed the code so I removed the appliedScaleFactor and I have

`
void HexBlocker::scaleGeometry()
{
    if(convertToMeters <= 0)    // sanity check
    {
        return;
    }
    //Since SetUserTransform overwrites the previous transform we don't
    //need to keep track of previous scales.
    vtkSmartPointer<vtkTransform> transform = vtkSmartPointer<vtkTransform>::New();
    if(scaledGeometry>0)
        transform->Scale(1,1,1);
    else
        transform->Scale(convertToMeters, convertToMeters, convertToMeters);
    GeoActor->SetUserTransform(transform);
    this->render();
}
`


Let me know if you would like me to push these changes.

**Comment by leorosa** [comment]
Hi there,

Thanks. I'll take a look at try.github.io/

About having "appliedScaleFactor": maybe it was too cautious to have it, considering a cenario where the user were constantly changing the scale. This is not expected to happen. In that case, I think that my implementation was wrong, as it did not recovered the geometry to its original size before scaling it again.

I think that it makes sense to have different scales for the mesh and geometry. One 'elegant' solution to the problem above would be to maintain visible only the mesh scale (convertToMeters) above the points list -- a check box there cluttered the GUI, no? We could have another menu item, to scale the geometry. How about a menu 'Tools' to group these scaling commands?

By the way, if a geometry was drawn in meters, and the mesh in milimiters (convertToMeters 0.001), the factor to scale the geometry would be 1000, right?

Thanks,
Leonardo Rosa

**Comment by nicolasedh** [comment]
>About having "appliedScaleFactor": maybe it was too cautious to have it, considering a cenario where the user were constantly changing the scale. This is not expected to happen. In that case, I think that my implementation was wrong, as it did not recovered the geometry to its original size before scaling it again.

Yes I think I'm a bit to blame here as well. Actually everytime we call `SetUserTransform` the previous scale is forgotten/reset. So the user can reset the scale as manytimes as he/she likes.

>I think that it makes sense to have different scales for the mesh and geometry. One 'elegant' solution to the problem above would be to maintain visible only the mesh scale (convertToMeters) above the points list -- a check box there cluttered the GUI, no? We could have another menu item, to scale the geometry. How about a menu 'Tools' to group these scaling commands?

This sounds perfect! Would you like to implement id? 

>By the way, if a geometry was drawn in meters, and the mesh in milimiters (convertToMeters 0.001), the factor to scale the geometry would be 1000, right?

Yes I think so. But don't hold me responsable ;-)

**Comment by leorosa** [comment]
Nice -- sure, I can do that. Maybe not in time for reviewing today ;-)

**Comment by leorosa** [comment]
Well, it was faster than I thought. Could you test and see if it is ok?

I also changed the signal of VerticeEditorWidget::ui->scaleFator, from returnPressed() to editingFinished() -- it could be confusing, having a value displayed, but another in effect because someone forgot to press <enter>.

**Comment by nicolasedh** [comment]
Kewl! I'll have  a look!

**Comment by nicolasedh** [comment]
This works great!

Really nice work! I really like the new mesh scale settings. A lot more convenient. And having the scale dialog in the menu is really good as well!

So thank you for your work!
Nicolas

**Comment by leorosa** [comment]
Thanks -- I think it is a lot better than the previous implementation.
Next, I'll see if it is possible to 'snap' the points to surface.

Leonardo.

**Comment by nicolasedh** [comment]
That sounds great! Good luck! Let me know if you have any questions!

**Pull request merged**
