### PR TITLE
Utilize existing vertices for a extruded block, if it is aligned to the existing blocks.

### PR DESCRIPTION
**Pull request by leorosa**
Hi,

I have changed the code for patch extrusion, in order to make the new (extruded) blocks connected to the previous ones. This behavior provides a more straightforward work flow, when extruding many (aligned) patches. The best solution would be to handle the extrusion of a list of patches, though.

Regards,
Leonardo Rosa

### CODE REVIEW

**Comment by nicolasedh** [comment]
Hi Leonardo,

This is great! Thanks for contributing!

Just one question though, should we use a tolererance? 
Maybe a fraction of the bounding box or the extrude distance.

I wonder what happens if we end up with two blocks sharing four vertices but we havn't merged the two patches. (The patches all have an owner block and possible an neighbour).

I'll do some testing during the weekend and report back.
Best Regards
Nicolas

**Comment by leorosa** [comment]
H Nicolas,

> Hi Leonardo,
>
> This is great! Thanks for contributing!
>
My pleasure. I wish I knew more of VTK, as there are other improvements
that I wanted to have in your program.

> Just one question though, should we use a tolererance?
> Maybe a fraction of the bounding box or the extrude distance.
>
An explanation: I did this small change to fix my workflow, without
disrupting (a lot) the original behavior. I think that there may be cases
when two blocks need their own patches (e.g., with an internal wall).

With this in mind, perhaps a better solution would be (1) to check the
position of all points in all 5 'new' patches, and if the distance of two
patches is lower than some tolerance, (2) *asks* the user, if he wants to
merge them?

> I wonder what happens if we end up with two blocks sharing four vertices
> but we havn't merged the two patches. (The patches all have an owner block
> and possible an neighbour).
>
With the proposed changes, we may have two blocks sharing four vertices --
that was my intention. I haven't seen/changed any code to merge the two
patches, but they seem to be merged somehow in hexBlocker. Anyhow, there is
no need to define internal patches for blockMesh.

> I'll do some testing during the weekend and report back.
> Best Regards
> Nicolas
>
Best regards,
Leonardo

**Comment by nicolasedh** [comment]
Hi again!

>My pleasure. I wish I knew more of VTK, as there are other improvements that I wanted to have in your program.

Don't worry about it. I knew nothing of VTK and very little C++ when I started this project. My main objective was to learn something. I also wanted to figure out and implemented my own version of O-grid. But I never got so far. These days I've had other spare time projects so hexBlocker has gotten very little attention. I was thinking about rewriting the hole thing in python but we'll se about that. For now hexBlocker is good enough for me. If I need something more complicated I got to salome/snappy or cfMesh. In any case if you give some of those "other improvements" a shot I'd be happy to help or offer advice!

>I think that there may be cases
when two blocks need their own patches (e.g., with an internal wall).
...
>I haven't seen/changed any code to merge the two
patches, but they seem to be merged somehow in hexBlocker. Anyhow, there is
no need to define internal patches for blockMesh.

Yes you are right there seems to be a feature that automerges patches that I forgot about. As you mention one might sometimes want to create a baffle or AMI patch. "internal patches" kan still be selected as BCs so the only problem is if you want the mesh to be non-conformal. Since there is no split patch feature, we could breake something. Although it can be worked around after blockMesh with splitMesh. So not a problem at all I say.

>With this in mind, perhaps a better solution would be (1) to check the
position of all points in all 5 'new' patches, and if the distance of two
patches is lower than some tolerance, (2) *asks* the user, if he wants to
merge them?

or (3) have a checkbox "merge" when we set extrude distance. Perhaps with a absolute default tolerance. 

In any case I think you addition is great so I'll merge it in! We can add the other stuff later.

Best Regards
Nicolas

**Comment by leorosa** [comment]
> Merged #3 <https://github.com/nicolasedh/hexBlocker/pull/3>.
>
Cool. Thanks!

> Don't worry about it. I knew nothing of VTK and very little C++ when I
> started this project. My main objective was to learn something. I also
> wanted to figure out and implemented my own version of O-grid. But I never
> got so far. These days I've had other spare time projects so hexBlocker has
> gotten very little attention. I was thinking about rewriting the hole thing
> in python but we'll se about that. For now hexBlocker is good enough for
> me. If I need something more complicated I got to salome/snappy or cfMesh.
> In any case if you give some of those "other improvements" a shot I'd be
> happy to help or offer advice!
>
Although (here) freecad/snappyHexMesh is good for complex geometries, I
still prefer a completely hexahedral mesh with gradual refinement. Having
done some meshes 'by hand' with blockMesh, I am really impressed with the
functionality already present in hexBlocker.

I will take a time to look into VTK, perhaps it already have methods to:
- translade points (there is vtkMath::Add() )
- rotate points
- scale points

More 'advanced' features would be
- display a geometry
- 'snap' points to the nearest surface

Then I think I'm done. Perhaps split blocks...

Anyhow, thanks again.

**Comment by nicolasedh** [comment]
>- translade points (there is vtkMath::Add() )
- rotate points
- scale points

Yes there are "filters" built in to VTK. And I just saw this: 
http://www.vtk.org/doc/nightly/html/classvtkGeneralTransform.html
  
> More 'advanced' features would be
- display a geometry

This has been on my 2do list as well. Reading and displaying a geometry shouldn't be too hard. Here's an example http://www.vtk.org/Wiki/VTK/Examples/Cxx/IO/ReadSTL . Letting the user interact with the geometry might be more tricky. 

> - 'snap' points to the nearest surface

I do think projection is available in VTK. Here's an example of how it could work.
http://www.vtk.org/Wiki/VTK/Examples/Cxx/PolyData/CellLocator 
or
http://www.vtk.org/Wiki/VTK/Examples/Cxx/SimpleOperations/ProjectPointPlane

Once this is accomplished my idea was to implement polyLines for edges and project them onto a surface. But in order to really work well, blockMesh would have to be able to snap patches to surfaces. Perhaps snappy could be used.

/N

**Comment by leorosa** [comment]
Thanks for the links! I'll see them, and try to make something useful.

**Pull request merged**
