### PR TITLE
Add support to snap vertices to the closest point in a geometry.

### PR DESCRIPTION
**Pull request by leorosa**
Hi Nicolas,

I have added support to project vertices to surfaces. Two remarks:
1. There is a kind of a "hack" at `slotEndSelectVertices()`, made to use `slotStartSelectVertices()` without creating a new toolbox when calling `slotSnapVertices()` in `MainWindow.cpp`. I hope that it is OK;
2. Vertices are projected to the unscaled geometry. I'll investigate further, how to use the scaled positions.

If you feel kind enough, could you draw a better icon?

Thanks!
Leonardo Rosa

### CODE REVIEW

**Comment by nicolasedh** [comment]
Hi!

This sounds great! Sorry for not responding sooner it's been a busy weekend. I'll try to find time tonight to test and review the code.

I'll post back!

Nicolas

**Comment by nicolasedh** [comment]
Thanks for the change! It really looks great! 

I drew a ... let's say different icon. I don't know if it's any better though. Feel free to modify! I make the icons in inkscape. I also keep the svg files in the repo incase one want's to change the icons. 

You where talking of maybe implementing a function for splitting blocks. I've had a couple of ideas. Let me know if you'd like me to elaborate. 

Best Regards
Nicolas

**Comment by leorosa** [comment]
Thanks! The icon is better, yes.

I'll open an issue, to discuss the splitting blocks there, ok?

By the way, I've seen that you connected and disconnected signals in slots -- I've used this approach to get rid of that ugly "isToSnap" hack made in the original implementation of this feature.

Regards,
Leonardo Rosa

**Comment by nicolasedh** [comment]
Very good!

Yes I usually have to connect and disconnected in slots. I'm a bit worried
that I'll get messy but sometimes it's unavoidable.

I do try too keep GUI and VTK as separate as possible. I think they call it
"model and data". But it seems you've already seen that :-).

I'll pull you're changes later tonight.

Best regards
Nicolas
Den 15 feb. 2016 01:06 skrev "leorosa" <notifications@github.com>:

**Comment by leorosa** [comment]
Yes, I've seen the separation between GUI and VTK -- it is really better this way.

By the way: do you still entertain the idea of "rewriting the whole thing in python"?

**Comment by nicolasedh** [comment]
Yes I still entertain the idea. Haven't done anything about it though.
Mostly because of other spare time projects.

But I'm also having small nagging feeling that tells me that it won't be as
easy as I first thought. The VTK python wrappers aren't all that fun to
work with. It's almost as bad as writing in C++.

But pyqt is really nice. And I think python list will really help. Right
now the C-code has a lot of indecies to objects in a collection. It really
gets me dizzy. I would prefer to work objects (or their reference) with
could work well in python. I'm not so sure now though.


Den 15 feb. 2016 11:33 skrev "leorosa" <notifications@github.com>:

**Comment by leorosa** [comment]
Cool. I asked because, "after" this split blocks feature, I think that the logical step would be to get rid of some bugs. However, C++ errors are not that helpful, and using gdb wouldn't add fun to it.

Well, it appears that I'm trying to avoid one problem creating another, but I just wanted to let you know, that I could give you a hand (or two) with a 'translation'.

**Comment by nicolasedh** [comment]
That is cool! Yes there are quite a few bugs. Very often bc's list the
same  patch several times.

And of course hexBlocker doesn't support codedStream. I have been meaning
to include OpenFoam lib to be able to read the dictionary.

It would be fun to start that translation to python. I don't I need many
hours for the current project I'm working with. But I can only work 3-5
hours per week. So it will take me a while. In real time. (I'm writing my
own hdf5 writer that supports polyhedrals.)

I'll let you know when and if I start. It would be good to talk things
through on what should be changed and what to keep.

I actually have a dream of only using VTK. No Qt. The menus would pop up
lika a mind map on top of the 3D window when the user hits space. But
that's a bit to much of a dream I think.

As for gdb. I actually think that qtcreators debugging and code stepping is
really good. Have you tried it?
Den 15 feb. 2016 8:00 em skrev "leorosa" <notifications@github.com>:

**Comment by leorosa** [comment]
Floating items when hovering near patches / edges / vertices / blocks? Yes, it appears to be a bit too fancy ;)

Well, I was thinking aloud about python, but perhaps it would be easier to develop on it. For now, thanks for the suggestion of qtcreator; I didn't knew it has a debugger. It could be a valueable tool, as I'm using some spare time to do these things.

Thanks!

**Comment by nicolasedh** [comment]
Yeah, it would be hard to code and I'm not even sure I would like it =)

Yes qtcreater is really nice. Has good autocompletion and you can
ctrl-click and it will take you right to the source/header.
A tip is to open the CMakeList.txt and it will understand it's a project.
Then under the "project" tab to the left set the build directory to where
you the install-script created it. Qtcreator will ask you to run cmake but
you don't need to add any variables to cmake since it will read them from
the previous build.

If you've turned on debug in the install script set that build directory
(you can have different build configurations in the project tab). Set the
run executable to the debug version. Now when you run in debug mode (F5)
qtcreator supports breakpoints and variable inspection.


Best Regards
Nicolas

2016-02-16 1:50 GMT+01:00 leorosa <notifications@github.com>:

**Comment by leorosa** [comment]
Thanks a lot for the tips!

Speaking of 'fanciness': have you noticed that, depending on the size of the blocks, edges tend to disappear? Have you tried to display them using lines/arcs instead of tubes?

Leonardo

**Comment by nicolasedh** [comment]
Yes I have noticed. I originally opted for tubes since regular lines turned
out to be really hard to pick.

Selecting the right radius is really tricky. Specially if you have long and
thin blocks. Say 2D.

I haven't figured out a better solution yet. Perhaps VTK 6 works better
with lines instead of edges but I haven't tried yet.

/N

2016-02-18 2:47 GMT+01:00 leorosa <notifications@github.com>:

**Pull request merged**
