### PR TITLE
Read STL files

### PR DESCRIPTION
**Pull request by leorosa**
Hi Nicolas,

I've added support to read STL files into hexBlocker. Only one file can be displayed/hidden.

Although I have only used the vtk example that you showed me, it appears to work more or less as intended. Beware that not all files can be read: sadly, vtk 5.10 may have a bug that prevents the reading of ASCII STL files.

Best regards,
Leonardo Rosa

### CODE REVIEW

**Comment by nicolasedh** [comment]
Hi!

Another great change! I'll test this now. 

I have tried to update hexblocker to use vtk6 but they introduce a lot of things which aren't backwards compatible with vtk5 so it will take me a while to update. For now I'm trying the system vtk of fedora 23.

I'll post back if sucessful.

/N

**Comment by nicolasedh** [comment]
Hi, 
I've updated projects so it's VTK6 compatible. And ascii stl works.

However I haven't changed the install script. It still uses the old vtk.

I'll see if I can't find a fix.

/N

**Comment by nicolasedh** [comment]
I have now changed the install script so it uses vtk 6.

It would be great if you could test this on your system.

/Nicolas

**Comment by leorosa** [comment]
Cool! Now the reader is fully working -- and the acsii ones do not crash the program anymore :)

However, the (new) VTK libraries were not found when trying to execute the program. I had to manually set LD_LIBRARY PATH to be able to run hexBlocker (lubuntu system here).

Leonardo

**Comment by nicolasedh** [comment]
Hi, 

You are right. Now when I built I get the same error. There should be an option in CMake to set rpath. I'll have a look.

/N

**Comment by nicolasedh** [comment]
I've pushed a minor change to CMakeLists. It should work now

For some reason a commented out the line telling cmake to set RPATH and forgot point it to the new vtk.

Thank you for testing it!


Now here is a question for you. Have you noticed that whenever we rotate the modell the rotation is about the center of gravity. Not where the user clicked.  ParaView has the same issue. If you have any ideas on how to change this please let me know =). I noticed this when I imported an STL which was rather long. It's easy to get lost when rotating.

**Comment by leorosa** [comment]
Hi,

Yes, I've also noticed that the axis 'appear' to be not exactly aligned with the blocks. I don't remember if this was occurring with VTK 5.10. I'll see if I find something, but, in this regard: is it possible/easy to allow the viewer to use "parallel projection", instead of "perspective" (2D vs 3D in ParaView)?

I've found these methods in nightly -- may be there is something as useful as them in vtk 6.3:
http://www.vtk.org/doc/nightly/html/classvtkCamera.html
void vtkCamera::OrthogonalizeViewUp ( )
virtual void vtkCamera::GetFocalPoint ( )

**Comment by leorosa** [comment]
I noticed another 'problem'. Imagine that you have a STL file, and decides to design the mesh using milimiters. The blocks will be 'off', compared to the geometry. I'm thinking in change a bit the scaling, which currently is done when saving blockMeshDict, to the following:

* assume that the drawing is done in meters, from the beginning (same as current code);
* display "convertToMeters" value above the points list;
* have a tool to set this value any time;
* scale the geometry, to match the points' scale;

What do you think? This change will also avoid the need to ask the scale every time blockMeshDict is saved.

**Comment by nicolasedh** [comment]
I'll have a look att parallel projection. I've had it on my 2dolist for quite a while but never really started with it. Since ParaView can do it then so should we =)

I think your proposal sounds excelent! 

Perhaps add a checkbox next to "convertToMeters" which let's the user select if the geometry should be scaled with the same factor. Sometimes the STL is in mm and sometimes it's m. I'm not sure one likes the geometry to be scaled every time. 
But then I wonder what happens (or should happen) when the user unticks the box?

**Comment by nicolasedh** [comment]
I changed so we always set parallel projection. Just pushed the changes.

Let me know if you like it.

Nicolas

**Comment by leorosa** [comment]
Sure -- personally, I prefer parallel projection.

Regarding the geometry size,
> But then I wonder what happens (or should happen) when the user unticks the box?
would it "unscale", or rather scale using 1/convertToMeters?

**Comment by leorosa** [comment]
By the way, have you seen this?

http://www.vtk.org/doc/nightly/html/classvtkCamera.html#a9a3cac6137d4e4c92a58b631706b44e1

> cam->SetFreezeFocalPoint(0);

appears to "correct" the off-center rotation of the model.

**Comment by nicolasedh** [comment]
Yes I agree the only situation I don't use parallel projection is when I
forgot to turn it on in paraview. In older versions there was an option you
could set which persisted during sessions. But they moved the option so you
set it in the properties panel. Weird choice.

Yes "unscale" with be less error prone I think. We could have a class data
member "appliedScaleFactor " then every time we scale that factor is
multiplied.

Then upon "untick" we scale with 1/appliedScaleFactor. That would fix cases
where the user first sets a scalefactor and then changes his/her mind and
sets a new one. In that case I guess the reasonable response would be to
unscale the old factor and then rescale. (by multiplying the scale factors
and then scaling not by scaling twice).



2016-02-08 16:52 GMT+01:00 leorosa <notifications@github.com>:

**Comment by nicolasedh** [comment]
>By the way, have you seen this?
>
>http://www.vtk.org/doc/nightly/html/classvtkCamera.html#a9a3cac6137d4e4c92a58b631706b44e1
>
>cam->SetFreezeFocalPoint(0);
>appears to "correct" the off-center rotation of the model.

I did try it and it feels better! Thank's!

**Comment by leorosa** [comment]
Heh, I spent a lot of time looking for this lost option in ParaView, before noticing the "2D" button in newer versions.

Well, I see that there is "exporter->conv2meter". But I haven't seen the value of convertToMeters read from blockMeshDict. Yes, perhaps we need a new data member, and set it when reading the dictionary?

**Comment by nicolasedh** [comment]
I know! I spent quite a lot of time as well!

Well perhaps we could reuse the one in conv2meter. 

Later on we could make Geometry.cpp an own class and have the the GeoActor and the scale factor as members. Then that class would have it's own scale function.

/N

**Comment by leorosa** [comment]
Hi,

I used some of the code, and made another PR.
You are right: it makes sense to 'break' the code in smaller pieces. Well, firstly, lets see if it works now.

Thanks!

**Pull request merged**
